development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rorla_mailgun_api_key: <%= ENV["RORLA_MAILGUN_API_KEY"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
